[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
zuvi = "5YUDDtqCHn11CgvmqNe3F2BgXzq68WeQJasv8hQFrux1"

[programs.devnet]
zuvi = "5YUDDtqCHn11CgvmqNe3F2BgXzq68WeQJasv8hQFrux1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/zuvi.ts"
initialize = "yarn run ts-node tests/initialize.ts"